language: cpp

dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - catch
    - doxygen
    - libboost-all-dev
    - libcpprest-dev
    - libfabric-dev
    - libibverbs-dev
    - libkmod-dev
    - libnuma-dev
    - libpci-dev
    - librdmacm-dev
    - libtool-bin
    - libzmq3-dev
    - valgrind

env:
  global:
    - LLVM_VERSION=3.6.2
    - LLVM_ARCHIVE_PATH=$HOME/clang+llvm.tar.xz
    - LIBFABRIC_ARCHIVE_PATH=$HOME/libfabric-1.10.1.tar.bz2

before_install:
    - wget http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz -O $LLVM_ARCHIVE_PATH
    - mkdir $HOME/clang+llvm
    - tar xf $LLVM_ARCHIVE_PATH -C $HOME/clang+llvm --strip-components 1
    - export PATH=$HOME/clang+llvm/bin:$PATH
    - wget https://github.com/ofiwg/libfabric/releases/download/v1.10.1/libfabric-1.10.1.tar.bz2 -O $LIBFABRIC_ARCHIVE_PATH
    - mkdir $HOME/libfabric
    - tar xzf $LIBFABRIC_ARCHIVE_PATH -C $HOME/libfabric --strip-components 1
    - PWD_ADDR=$(pwd) && cd $HOME/libfabric && ./configure  && make && cd $PWD_ADDR
    - export PATH=$PATH:$HOME/libfabric/include:$HOME/libfabric/src/.libs

before_script:
  - contrib/merge-dependencies
  - mkdir build && cd build
  
script:
  - cmake ..
  - make
  - make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - if [ "$CXX" = "g++-8.3" ]; then cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && make -j4 && make coveralls; fi
