language: cpp

dist: bionic

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
    - catch
    - doxygen
    - libboost-all-dev
    - libcpprest-dev
    - libfabric-dev
    - libibverbs-dev
    - libkmod-dev
    - libnuma-dev
    - libpci-dev
    - librdmacm-dev
    - libtool-bin
    - libzmq3-dev
    - valgrind
    - mpich
    
env: MPI=YES
    
before_install:
  - pip install --user cpp-coveralls

before_script:
  - contrib/merge-dependencies
  - mkdir build && cd build
  
script:
  - cmake ..
  - ./configure --enable-gcov
  - make
  - make check
#  - make CTEST_OUTPUT_ON_FAILURE=1 test

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
  #- cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. && make -j4 && make coveralls;
